# Generated by Django 5.1.3 on 2024-11-22 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('columns', models.JSONField()),
                ('status', models.CharField(max_length=255)),
                ('error_message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Analyses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(max_length=255)),
                ('parameters', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('error_message', models.CharField(max_length=255)),
                ('dataset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.analyses')),
            ],
        ),
    ]
