# Generated by Django 5.1.3 on 2024-11-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_analyses_status_columnmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyses',
            name='model_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
