# Generated by Django 5.1.3 on 2024-12-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_analyses_model_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyses',
            name='confusion_matrix',
            field=models.TextField(blank=True, null=True),
        ),
    ]
