# Generated by Django 5.1.3 on 2024-12-01 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_analyses_confusion_matrix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyses',
            name='confusion_matrix',
        ),
    ]
